components:
  schemas:
    HTTPError:
      properties:
        detail:
          type: object
        message:
          type: string
      type: object
info:
  title: Newsletter Service
  version: 0.1.0
openapi: 3.0.3
paths:
  /sayHello/{name}:
    get:
      parameters:
      - in: path
        name: name
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            text/html:
              schema:
                type: string
          description: Successful response
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Not found
      summary: Say Hello
tags: []
