components:
  schemas:
    ValidationError:
      properties:
        detail:
          properties:
            <location>:
              properties:
                <field_name>:
                  items:
                    type: string
                  type: array
              type: object
          type: object
        message:
          type: string
      type: object
info:
  title: Greeting Service
  version: 0.1.0
openapi: 3.0.3
paths:
  /formatGreeting:
    get:
      parameters:
        - in: query
          name: description
          required: false
          schema:
            type: string
          examples:
            SUCCESS:
              value: Independent Technical Coach, YouTuber, creator of Samman Coaching, Author
        - in: query
          name: name
          required: true
          schema:
            type: string
          examples:
            SUCCESS:
              value: EmilyBache
        - in: query
          name: title
          required: false
          schema:
            type: string
          examples:
            SUCCESS:
              value: Miss.
      responses:
        '200':
          content:
            text/html:
              schema:
                type: string
              examples:
                SUCCESS:
                  value: Hello, Miss. EmilyBache. Independent Technical Coach, YouTuber, creator of Samman Coaching, Author is my favourite person.
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: Validation error
      summary: Format Greeting
tags: []
