components:
  schemas:
    HTTPError:
      properties:
        detail:
          type: object
        message:
          type: string
      type: object
    PersonOut:
      properties:
        description:
          nullable: true
          type: string
        name:
          type: string
        title:
          nullable: true
          type: string
      type: object
info:
  title: Users Service
  version: 0.1.0
openapi: 3.0.3
paths:
  /getPerson/{name}:
    get:
      parameters:
      - in: path
        name: name
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonOut'
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Bad Input
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Not found
      summary: Get Person Http
tags: []
